# Logitech F710 wireless controller
# Deadman (enable) button: Right Trigger
# D<>X button (located on the back panel) must be set to D
/**:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: [7]  # RT
      axis_mappings:
        linear-x:
          axis: 3
          scale: 0.5
          offset: 0
        linear-y:
          axis: 2
          scale: -0.5
          offset: 0
        angular-z:
          axis: 0
          scale: -3
          offset: 0
    anomaly_pub:
      type: topic
      interface_type: "std_msgs/msg/Bool"
      topic_name: anomaly
      deadman_buttons: [6, 2]  # RT
      message_value:
        data:
          value: true

